apiVersion: v1
kind: Service 
metadata: 
    name: {{ .Values.app.name }}-service
spec:
    selector: 
      app: {{ .Values.app.name }}-{{ .Values.app.color }}
    ports:
      - protocol: TCP 
        port: 80
        targetPort: {{ .Values.app.port }}
    type: ClusterIP