name: CI/CD 

on:
    push:
        branches:
          - main 

env: 
    APP_NAME: blue-green-app
    DOCKER_IMAGE: anarkatomica1996/blue-green-app
    CLUSTER_NAMESPACE: default

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest 

        steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build Docker image
          run: |
            docker build -t $DOCKER_IMAGE:${{ github.run_number }} .

        - name: Push Docker image
          run: |
            docker push $DOCKER_IMAGE:${{ github.run_number }}

        - name: Set up kubeconfig
          uses: azure/setup-kubectl@v3
        
        - name: Configure kubectl 
          run: |
            echo "${{ secrets.KUBECONFIG }}" > kubeconfig
            export KUBECONFIG=$PWD/kubeconfig

        - name: Determine inactive color
          id: inactive
          run: |
            ACTIVE_COLOR=$(kubectl get svc $APP_NAME-service -o jsonpath="{.spec.selector.app}" | grep -o "blue\|green")
            if ["$ACTIVE_COLOR" = "blue" ]; then
              echo "color=green" >> $GITHUB_OUTPUT
            else
              echo "color=blue" >> $GITHUB_OUTPUT
            fi

        - name: Deploy to inactive environment
          run: |
            helm upgrade --install $APP_NAME-${{ steps.inactive.outputs.color }} ./helm-chart \
              --set app.color=${{ steps.inactive.outputs.color }} \
              --set app.image.tag=${{ github.run_number }}

        - name: Health check
          run: |
            COLOR=${{ steps.inactive.outputs.color }}
            URL=http://$COLOR.$APP_NAME.svc.cluster.local/health
            STATUS=$(curl -s -o /dev/null -w '%{http_code}' $URL)
            if [ "$STATUS" != "200" ]; then
              echo "Health check failed on $COLOR"
              exit 1
            fi

        - name: Switch traffic to inactive
          run: |
            COLOR=${{ steps.inactive.outputs.color }}
            kubectl patch svc $APP_NAME-service -p "{\"spec\":{\"selector\":{\"app\":\"$APP_NAME-$COLOR\"}}}"